use trident_fuzz::fuzzing::*;

#[derive(Default)]
pub struct AccountAddresses {
    pub vault: AddressStorage,
    pub shares_mint: AddressStorage,
    pub asset_mint: AddressStorage,
    pub deposit_vault: AddressStorage,
    pub redemption_escrow: AddressStorage,
    pub nav_oracle: AddressStorage,
    pub authority: AddressStorage,
    pub manager: AddressStorage,
    pub system_program: AddressStorage,
    pub token_2022_program: AddressStorage,
    pub asset_token_program: AddressStorage,
    pub associated_token_program: AddressStorage,
    pub rent: AddressStorage,
    pub user_0: AddressStorage,
    pub user_1: AddressStorage,
    pub user_2: AddressStorage,
    pub user_3: AddressStorage,
    pub user_4: AddressStorage,
    pub user_0_asset_account: AddressStorage,
    pub user_1_asset_account: AddressStorage,
    pub user_2_asset_account: AddressStorage,
    pub user_3_asset_account: AddressStorage,
    pub user_4_asset_account: AddressStorage,
    pub user_0_shares_account: AddressStorage,
    pub user_1_shares_account: AddressStorage,
    pub user_2_shares_account: AddressStorage,
    pub user_3_shares_account: AddressStorage,
    pub user_4_shares_account: AddressStorage,
    pub attestation_0: AddressStorage,
    pub attestation_1: AddressStorage,
    pub attestation_2: AddressStorage,
    pub attestation_3: AddressStorage,
    pub attestation_4: AddressStorage,
}
