[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
svs_1 = "Bv8aVSQ3DJUe3B7TqQZRZgrNvVTh8TjfpwpoeR1ckDMC"
svs_2 = "3UrYrxh1HmVgq7WPygZ5x1gNEaWFwqTMs7geNqMnsrtD"

[programs.localnet]
svs_1 = "SVS1VauLt1111111111111111111111111111111111"
svs_2 = "SVS2VauLt2222222222222222222222222222222222"
svs_3 = "SVS3VauLt3333333333333333333333333333333333"
svs_4 = "SVS4VauLt4444444444444444444444444444444444"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
# Run all tests: anchor test
# Run specific file: anchor test -- tests/svs-1.ts
# Run by pattern: anchor test -- "tests/svs-*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
