[fuzz.metrics]
enabled = true


[[fuzz.programs]]
address = "SVS1VauLt1111111111111111111111111111111111"
program = "../target/deploy/svs_1.so"

[[fuzz.programs]]
address = "CR2ccVacmbQ2DaXvR66W7gnmH7KuDCqbVW5VwnTczQUC"
program = "../target/deploy/svs_7.so"
