[fuzz.metrics]
enabled = true


[[fuzz.programs]]
address = "SVS1VauLt1111111111111111111111111111111111"
program = "../target/deploy/svs_1.so"

[[fuzz.programs]]
address = "6v6FHxx26oqjJEjZa3S2XiuWSuDbYScd9VB7kLa4yzmE"
program = "../target/deploy/svs_7.so"
