[package]
name = "derwa-wrapper"
version = "0.1.0"
description = "1:1 wrap/unwrap between permissioned cPOOL and freely-transferable dePOOL"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "derwa_wrapper"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["token", "associated_token"] }
spl-transfer-hook-interface = "0.9"
